# Generated by Django 3.2.3 on 2021-05-31 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FishingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=200)),
                ('location_details', models.TextField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('air_temp', models.IntegerField()),
                ('water_temp', models.IntegerField()),
                ('persons', models.IntegerField()),
                ('weather', models.CharField(max_length=200)),
                ('wind', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FishingTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FishSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FishCatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish_species', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('length', models.IntegerField()),
                ('fishing_technique', models.CharField(max_length=100)),
                ('fishing_technique_details', models.TextField()),
                ('lure', models.CharField(max_length=100)),
                ('lure_details', models.TextField()),
                ('fishing_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fishing_event', to='fishing_events.fishingevent')),
            ],
        ),
    ]
