# Generated by Django 3.2.3 on 2021-06-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishing_events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishcatch',
            name='fishing_technique',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='fishcatch',
            name='fishing_technique_details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fishcatch',
            name='length',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='fishcatch',
            name='lure',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='fishcatch',
            name='lure_details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fishcatch',
            name='weight',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='fishingevent',
            name='air_temp',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='fishingevent',
            name='end_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='fishingevent',
            name='location_details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fishingevent',
            name='persons',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='fishingevent',
            name='start_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='fishingevent',
            name='water_temp',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='fishingevent',
            name='weather',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='fishingevent',
            name='wind',
            field=models.IntegerField(blank=True),
        ),
    ]
