# Generated by Django 3.2.3 on 2021-06-02 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishing_events', '0002_auto_20210601_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fishingtechnique',
            old_name='name',
            new_name='key',
        ),
        migrations.RenameField(
            model_name='fishspecies',
            old_name='name',
            new_name='key',
        ),
        migrations.RenameField(
            model_name='lure',
            old_name='name',
            new_name='key',
        ),
        migrations.RenameField(
            model_name='weatheroption',
            old_name='name',
            new_name='key',
        ),
    ]
