# Generated by Django 3.2.3 on 2021-06-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishing_events', '0004_auto_20210602_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishingevent',
            name='date',
            field=models.DateField(default='YYYY-MM-DD'),
        ),
    ]
