# Generated by Django 3.2.3 on 2021-06-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishing_events', '0005_alter_fishingevent_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishingevent',
            name='date',
            field=models.DateField(default='%Y-%m-%d'),
        ),
    ]
