# Generated by Django 3.2.3 on 2021-06-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishing_events', '0008_auto_20210608_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishcatch',
            name='length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fishcatch',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
